import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Desafío Técnico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (    
    <html lang="en">
      <body className="bg-slate-900 flex h-full">
        <div className="max-w-screen flex flex-col mx-auto size-full">
          <header className="mb-auto flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full text-sm py-4">
            <nav className="w-full px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8" aria-label="Global">
              <div className="flex items-center justify-between">
                <Link href="/">
                  <p className="flex-none text-xl font-semibold text-white focus:outline-none focus:ring-1 focus:ring-gray-600" aria-label="Brand">Desafío</p>
                </Link>
                <div className="sm:hidden ml-64">
	                <div className="w-[150px] text-gray-900 dark:text-gray-100">
	                  <div className="relative w-full group">
	                    <button className="py-2.5 px-3 md:text-sm text-site bg-transparent rounded-lg inline-flex justify-center items-center border border-gray-700 hover:border-gray-600 focus:border-brand focus:outline-none focus:ring-0 peer flex items-center justify-between rounded font-semibold">
                        <svg className="hs-collapse-open:hidden flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="3" x2="21" y1="6" y2="6"/><line x1="3" x2="21" y1="12" y2="12"/><line x1="3" x2="21" y1="18" y2="18"/></svg>
                        <svg className="hs-collapse-open:block hidden flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
                      </button>
                    <div
                      className="absolute z-[99] top-[100%] left-[50%] translate-x-[-50%] rounded-md overflow-hidden shadow-lg min-w-[200px] w-max peer-focus:visible peer-focus:opacity-100 opacity-0 invisible duration-200 p-1 bg-gray-100 dark:bg-gray-800  border border-dimmed text-xs md:text-sm">
                      <div
                        className="w-full block cursor-pointer hover:bg-white dark:hover:bg-gray-900 dark:bg-gray-800 hover:text-link px-3 py-2 rounded-md">
                        <Link href="/">
                          <p className="font-medium text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-1 focus:ring-gray-600">Home</p>
                        </Link>
                      </div>
                      <div
                        className="w-full block cursor-pointer hover:bg-white dark:hover:bg-gray-900 dark:bg-gray-800 hover:text-link px-3 py-2 rounded-md">
                        <Link href="/posts">
                          <p className="font-medium text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-1 focus:ring-gray-600">Posts</p>
                        </Link>
                      </div>
                    </div>
	                </div>
                </div>
              </div>  
            </div>
            <div id="navbar-collapse-with-animation" className="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
              <div className="flex flex-col gap-5 mt-5 sm:flex-row sm:items-center sm:justify-end sm:mt-0 sm:ps-5">
                <Link href="/">
                  <p className="font-medium text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-1 focus:ring-gray-600">Home</p>
                </Link>
                <Link href="/posts">
                  <p className="font-medium text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-1 focus:ring-gray-600">Posts</p>
                </Link>
              </div>
            </div>
          </nav>
        </header>
      
        {children}
        
      </div>
  </body>
    </html>

  );
}
